# Generated by Django 3.0.5 on 2020-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
