# Generated by Django 3.0.5 on 2020-04-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20200428_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
