# Generated by Django 3.0.5 on 2020-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20200430_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
