# Generated by Django 3.0.5 on 2020-04-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20200428_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='ref',
            name='node',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ref',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='body',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
