# Generated by Django 3.0.5 on 2020-04-30 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ref',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='node.Node'),
        ),
        migrations.AddField(
            model_name='nodereport',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='node.Node'),
        ),
        migrations.AddField(
            model_name='nodereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodereports', to='node.Ref'),
        ),
        migrations.AddField(
            model_name='edgevote',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='node.Edge'),
        ),
        migrations.AddField(
            model_name='edgevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edgevotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='node.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='node.Node'),
        ),
    ]
