# Generated by Django 3.0.5 on 2020-04-30 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '0002_auto_20200430_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgevote',
            name='edge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edgevotes', to='node.Edge'),
        ),
        migrations.AlterField(
            model_name='nodereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodereports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refvote',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refvotes', to='node.Ref'),
        ),
    ]
